-- Create visitor table for tracking organization registration requests
CREATE TABLE IF NOT EXISTS public.visitor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  org_name TEXT NOT NULL,
  phone TEXT,
  is_active BOOLEAN DEFAULT true,
  CONSTRAINT visitor_email_check CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS visitor_email_idx ON public.visitor(email);

-- Create index on is_active for filtering
CREATE INDEX IF NOT EXISTS visitor_is_active_idx ON public.visitor(is_active);

-- Add RLS policies (visitor table is publicly writable for registration, but read-only for admins)
ALTER TABLE public.visitor ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (for registration form)
CREATE POLICY "Allow public insert for visitor registration"
  ON public.visitor
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Only super_admins can read visitor data
CREATE POLICY "Super admins can view all visitors"
  ON public.visitor
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'super_admin'
    )
  );

-- Only super_admins can update visitor data
CREATE POLICY "Super admins can update visitors"
  ON public.visitor
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'super_admin'
    )
  );

-- Comment on table
COMMENT ON TABLE public.visitor IS 'Stores registration requests from potential customers before they become organizations';
COMMENT ON COLUMN public.visitor.full_name IS 'Full name of the person requesting access';
COMMENT ON COLUMN public.visitor.email IS 'Email address for contact (must be unique)';
COMMENT ON COLUMN public.visitor.org_name IS 'Name of the organization they want to register';
COMMENT ON COLUMN public.visitor.phone IS 'Optional phone number';
COMMENT ON COLUMN public.visitor.is_active IS 'Whether this registration request is still active/pending';
